#!/usr/bin/env bash

touch /root/.gmusicfs
chmod 600 /root/.gmusicfs
echo "Script executed"
echo "Creating config file"
echo "[credentials]" >> /root/.gmusicfs
echo "username = ${GOOGLE_USERNAME}" >> /root/.gmusicfs
echo "password = ${GOOGLE_PASSWORD}" >> /root/.gmusicfs
echo "deviceId = ${GOOGLE_DEVICE_ID}" >> /root/.gmusicfs

echo "Starting gmusicFS"
gmusicfs -l /root/music

echo "Removing config"
rm /root/.gmusicfs
